In [ ]:
########now part 2: decode and train#######

In [ ]:
from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())

In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd
import math
import timeit
import matplotlib.pyplot as plt
#from preprocess_func_new import *
from matplotlib.image import imread
import os
from os.path import expanduser
%matplotlib inline


#tf.logging.set_verbosity(tf.logging.INFO)

In [2]:
# for auto-reloading external modules
# see http://stackoverflow.com/questions/1907993/autoreload-of-modules-in-ipython
%load_ext autoreload
%autoreload 2

In [3]:
batch_size=8
val_batch_size=batch_size
test_batch_size=batch_size

In [4]:
img_path = os.path.join('..','datasets','stixels')
img_path

'../datasets/stixels'

In [5]:
#train
tfrec_train_directory = os.path.join('..','datasets','stixels','train','tfrec_batch_size_'+str(batch_size))

In [6]:
#train
path_tfrecords_train_lst=[]
path_tfrecords_train = os.path.join(img_path, 'train')
for root, dirs, files in os.walk(tfrec_train_directory):
    for file in files:
        if '.tfrecord' in file:
            path_tfrecords_train_lst.append(os.path.join(tfrec_train_directory,file))
        else:
            print('WARNING: file ' + file + 'looks suspicious. does it belong here?')



In [7]:
H=370 
W=24
C=3
img_shape = (H, W, C)
num_classes = 47

In [8]:
def parse(serialized):
    # Define a dict with the data-names and types we expect to
    # find in the TFRecords file.
    # It is a bit awkward that this needs to be specified again,
    # because it could have been written in the header of the
    # TFRecords file instead.
    features = \
        {
            'image': tf.FixedLenFeature([], tf.string),
            'label': tf.FixedLenFeature([], tf.int64)
        }

    # Parse the serialized data so we get a dict with our data.
    parsed_example = tf.parse_single_example(serialized=serialized,
                                             features=features)

    # Get the image as raw bytes.
    image_raw = parsed_example['image']

    # Decode the raw bytes so it becomes a tensor with type.
    #######image = tf.decode_raw(image_raw, tf.int32) ####
    image = tf.image.decode_png(image_raw, channels=3, dtype=tf.uint16)
    #image = tf.cast(image, tf.int32)

    # The type is now uint8 but we need it to be float.
    
    image = tf.cast(image, tf.float32) ####
    
    # Get the label associated with the image.
    label = parsed_example['label']

    # The image and label are now correct TensorFlow types.
    return image, label

In [9]:
def input_fn(filenames, train, batch_size=batch_size, buffer_size=40000): #2048
    # Args:
    # filenames:   Filenames for the TFRecords files.
    # train:       Boolean whether training (True) or testing (False).
    # batch_size:  Return batches of this size.
    # buffer_size: Read buffers of this size. The random shuffling
    #              is done on the buffer, so it must be big enough.

    # Create a TensorFlow Dataset-object which has functionality
    # for reading and shuffling data from TFRecords files.
    dataset = tf.data.TFRecordDataset(filenames=filenames)

    # Parse the serialized data in the TFRecords files.
    # This returns TensorFlow tensors for the image and labels.
    dataset = dataset.map(parse)

    if train:
        # If training then read a buffer of the given size and
        # randomly shuffle it.
        dataset = dataset.shuffle(buffer_size=buffer_size)

        # Allow infinite reading of the data.
        num_repeat = None
    else:
        # If testing then don't shuffle the data.
        
        # Only go through the data once.
        num_repeat = 1

    # Repeat the dataset the given number of times.
    dataset = dataset.repeat(num_repeat)
    
    # Get a batch of data with the given size.
    dataset = dataset.batch(batch_size)

    # Create an iterator for the dataset and the above modifications.
    iterator = dataset.make_one_shot_iterator()

    # Get the next batch of images and labels.
    images_batch, labels_batch = iterator.get_next()

    # The input-function must return a dict wrapping the images.
    x = {'image': images_batch}
    y = labels_batch
    
    return x, y

In [10]:
def train_input_fn():
    return input_fn(filenames=path_tfrecords_train_lst, train=True)

In [11]:
def model_fn(features, labels, mode ,params):
    # Args:
    #
    # features: This is the x-arg from the input_fn.
    # labels:   This is the y-arg from the input_fn.
    # mode:     Either TRAIN, EVAL, or PREDICT
    # params:   User-defined hyper-parameters, e.g. learning-rate.
    
    # Reference to the tensor named "image" in the input-function.
    x = features["image"]
    # The convolutional layers expect 4-rank tensors
    # but x is a 2-rank tensor, so reshape it.
    net = tf.reshape(x, [-1,W,H,C])
    # First convolutional layer.
    net = tf.layers.conv2d(inputs=net, name='layer_conv1',
                           filters=64, kernel_size=(11,5),
                           padding='same', activation=tf.nn.relu)
    net = tf.layers.max_pooling2d(inputs=net, pool_size=(8,4), strides=1)
    #net = tf.nn.lrn(input=net, depth_radius=4, bias=1.0, alpha=0.001 / 9.0, beta=0.75, name='norm1')
    # Second convolutional layer.
    net = tf.layers.conv2d(inputs=net, name='layer_conv2',
                           filters=200, kernel_size=(5,3),
                           padding='same', activation=tf.nn.relu) #200
    #net = tf.nn.lrn(input=net, depth_radius=4, bias=1.0, alpha=0.001 / 9.0, beta=0.75, name='norm1')
    net = tf.layers.max_pooling2d(inputs=net, pool_size=(4,3), strides=1)    

    # Flatten to a 2-rank tensor.
    #net = tf.contrib.layers.flatten(net)
    # Eventually this should be replaced with:
    net = tf.layers.flatten(net)

    # First fully-connected / dense layer.
    # This uses the ReLU activation function.
    net = tf.layers.dense(inputs=net, name='layer_fc1',
                          units=512, activation=tf.nn.relu)     #1024
    
    # Second fully-connected / dense layer
    net = tf.layers.dense(inputs=net, name='layer_fc2',
                          units=512, activation=tf.nn.relu)   #2048
    
   
    # This is the last layer so it does not use an activation function.
    net = tf.layers.dense(inputs=net, name='layer_fc3',
                          units=47)

    # Logits output of the neural network.
    logits = net

    # Softmax output of the neural network.
    y_pred = tf.nn.softmax(logits=logits)
    
    # Classification output of the neural network.
    y_pred_cls = tf.argmax(y_pred, axis=1)

    if mode == tf.estimator.ModeKeys.PREDICT:
        # If the estimator is supposed to be in prediction-mode
        # then use the predicted class-number that is output by
        # the neural network. Optimization etc. is not needed.
        spec = tf.estimator.EstimatorSpec(mode=mode,
                                          predictions=y_pred_cls)
    else:
        # Otherwise the estimator is supposed to be in either
        # training or evaluation-mode. Note that the loss-function
        # is also required in Evaluation mode.
        
        # Define the loss-function to be optimized, by first
        # calculating the cross-entropy between the output of
        # the neural network and the true labels for the input data.
        # This gives the cross-entropy for each image in the batch.
        cross_entropy = tf.nn.sparse_softmax_cross_entropy_with_logits(labels=labels,
                                                                       logits=logits)

        # Reduce the cross-entropy batch-tensor to a single number
        # which can be used in optimization of the neural network.
        loss = tf.reduce_mean(cross_entropy)

        

        '''
        another example for lr decay
        starter_learning_rate = 0.01
        learning_rate = tf.train.exponential_decay(starter_learning_rate, global_step=10000,
                                                   decay_steps=10000, decay_rate=0.5, staircase=True)
        # Passing global_step to minimize() will increment it at each step.
        learning_step = (tf.train.GradientDescentOptimizer(learning_rate)
                         .minimize(...my loss..., global_step=global_step)
        '''
                         
        '''
        lr = 0.01
        step_rate = 10000
        decay = 0.5

        global_step = tf.Variable(0, trainable=False)
#         increment_global_step = tf.assign(global_step, global_step + 1)
        learning_rate = tf.train.exponential_decay(lr, global_step, step_rate, decay, staircase=True)

        optimizer = tf.train.AdamOptimizer(learning_rate=learning_rate) #epsilon=0.01 in example
        train_op = optimizer.minimize(loss=loss, global_step=global_step)
        
        '''                            
        lr = 0.01
        step_rate = 1000
        decay = 0.5
        # global_step_var = tf.Variable(0, trainable=False)
        # increment_global_step = tf.assign(global_step, global_step + 1)

        learning_rate = tf.train.exponential_decay(lr, global_step=tf.train.get_or_create_global_step(), 
                                           decay_steps=step_rate, decay_rate=decay, staircase=True)
        
        #ORIGINAL:                 
        # Define the optimizer for improving the neural network.
        optimizer = tf.train.AdamOptimizer(learning_rate=learning_rate)#params["learning_rate"])
                
        # Get the TensorFlow op for doing a single optimization step.
        train_op = optimizer.minimize(loss=loss, global_step = tf.train.get_or_create_global_step())
        
        
        
        # Define the evaluation metrics,
        # in this case the classification accuracy.
        metrics = \
        {
            "accuracy": tf.metrics.accuracy(labels, y_pred_cls)
        }

        # Wrap all of this in an EstimatorSpec.
        spec = tf.estimator.EstimatorSpec(
            mode=mode,
            loss=loss,
            train_op=train_op,
            eval_metric_ops=metrics)
        
    return spec

In [12]:

params = {"learning_rate": 1e-4}


In [13]:
def make_dir_and_comment(model_dir):
    home = expanduser("~")
    log_name=os.path.join('logs/', model_dir + '.txt')
    
    if os.path.isdir(model_dir):
        print('INFO: dir with name ' + model_dir + ' already exist.')
    
    new_comment=input('Please add a comment\n')
    
    if os.path.exists(log_name):
        append_write = 'a' # append if already exists
    else:
        append_write = 'w' # make a new file if not
    
    model_log = open(log_name,append_write)
    model_log.write(home +' : '+ new_comment + '\n')
    model_log.close()
    return



In [14]:
model_dir = './ckpts_21_5_lenet_fc_512_512_b8_decayLR_1000' #'./ckpts_<day>_<month>_<architecture>_<main_change>'
make_dir_and_comment(model_dir) 
model = tf.estimator.Estimator(model_fn=model_fn,
                               params=params,
                               model_dir=model_dir)


Please add a comment
checking b8 with LR decay
INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_save_checkpoints_secs': 600, '_num_worker_replicas': 1, '_keep_checkpoint_every_n_hours': 10000, '_is_chief': True, '_service': None, '_save_checkpoints_steps': None, '_task_id': 0, '_tf_random_seed': None, '_save_summary_steps': 100, '_task_type': 'worker', '_evaluation_master': '', '_model_dir': './ckpts_21_5_lenet_fc_512_512_b8_decayLR_1000', '_keep_checkpoint_max': 5, '_num_ps_replicas': 0, '_log_step_count_steps': 100, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f24dbe099b0>, '_global_id_in_cluster': 0, '_session_config': None, '_master': ''}


In [15]:
model.train(input_fn=train_input_fn, steps=10000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 1 into ./ckpts_21_5_lenet_fc_512_512_b8_decayLR_1000/model.ckpt.
INFO:tensorflow:step = 0, loss = 9862.116
INFO:tensorflow:global_step/sec: 2.65804
INFO:tensorflow:step = 100, loss = 3.413661 (37.623 sec)
INFO:tensorflow:global_step/sec: 2.839
INFO:tensorflow:step = 200, loss = 3.4336715 (35.224 sec)
INFO:tensorflow:global_step/sec: 2.83256
INFO:tensorflow:step = 300, loss = 3.5464396 (35.304 sec)
INFO:tensorflow:global_step/sec: 2.83849
INFO:tensorflow:step = 400, loss = 3.8409648 (35.230 sec)
INFO:tensorflow:global_step/sec: 2.85649
INFO:tensorflow:step = 500, loss = 3.5927527 (35.008 sec)
INFO:tensorflow:global_step/sec: 2.83738
INFO:tensorflow:step = 600, loss = 3.9153426 (35.244 sec)
INFO:tensorflow:global_ste

#####DONE TRAIN######

In [ ]:
# VAL 

In [32]:
#val
path_tfrecords_val_lst=[]
path_tfrecords_val = os.path.join(img_path, 'val')
for root, dirs, files in os.walk(tfrec_val_directory):
    for file in files:
        if '.tfrecord' in file:
            path_tfrecords_val_lst.append(os.path.join(tfrec_val_directory,file))
        else:
            print('WARNING: file ' + file + 'looks suspicious. does it belong here?')

In [31]:
#val
tfrec_val_directory = os.path.join('..','datasets','stixels','val','tfrec_batch_size_'+str(val_batch_size))

In [30]:
def val_input_fn():
    return input_fn(filenames=path_tfrecords_val_lst, train=False)

In [ ]:
val_result = model.evaluate(input_fn=val_input_fn) ##need to reduce batch size for val and test

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2018-05-21-15:00:41
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from ./ckpts_21_5_lenet_fc_512_512_b8_decayLR_1000/model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


In [ ]:
val_result

In [ ]:
print("Classification val accuracy: {0:.2%}".format(val_result["accuracy"]))

In [ ]:
###test###

In [16]:
#only for showing pics with predictions later

sum_csv_test_path = os.path.join(img_path,'test', 'sum_csv')
labels_test=pd.read_csv(os.path.join(sum_csv_test_path,'labels_test.csv'))
test_names_list=list(labels_test['Name'])
image_paths_test=[]
for name in test_names_list:
    image_paths_test.append(os.path.join(img_path, 'test', name+'.png')) #maybe no need to add '.png'


In [ ]:
def test_input_fn():
    return input_fn(filenames=path_tfrecords_test, train=False)

In [ ]:
test_result = model.evaluate(input_fn=test_input_fn)

In [ ]:
test_result

In [ ]:
print("Classification test accuracy: {0:.2%}".format(test_result["accuracy"]))

In [ ]:
###pred###

In [17]:
#for pred later only
def load_images(image_paths):
    # Load the images from disk.
    images = [imread(path) for path in image_paths]
    # Convert to a numpy array and return it.
    return np.asarray(images)


In [24]:
#for pred later only ##TODO:SHUFFLE!

##TODO:SHUFFLE!

some_num=5000
some_images = load_images(image_paths=image_paths_test[20000:20000+some_num])
some_images_cls = np.array(labels_test['Label'])

In [25]:
print(some_images_cls)

[46 46 46 ... 46 46 46]


In [26]:
#check if this works TODO
predict_input_fn = tf.estimator.inputs.numpy_input_fn(
    x={"image": some_images.astype(np.float32)},
    num_epochs=1,
    shuffle=False)

In [27]:
predictions = model.predict(input_fn=predict_input_fn)

In [28]:
cls_pred = np.array(list(predictions))
cls_pred 

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from ./ckpts_21_5_lenet_fc_512_512_b8_decayLR_1000/model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


array([16, 16, 16, ..., 16, 16, 16])

In [29]:
np.histogram(cls_pred, bins=47)

(array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0, 5000,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0]),
 array([15.5       , 15.5212766 , 15.54255319, 15.56382979, 15.58510638,
        15.60638298, 15.62765957, 15.64893617, 15.67021277, 15.69148936,
        15.71276596, 15.73404255, 15.75531915, 15.77659574, 15.79787234,
        15.81914894, 15.84042553, 15.86170213, 15.88297872, 15.90425532,
        15.92553191, 15.94680851, 15.96808511, 15.9893617 , 16.0106383 ,
        16.03191489, 16.05319149, 16.07446809, 16.09574468, 16.11702128,
        16.13829787, 16.15957447, 16.18085106, 16.20212766, 16.22340426,
        16.24468085, 16.26595745, 16.28723404, 16.30851064, 16.32978723,
        16.35106383, 16.37234043, 16.39361702, 16.41489362, 16.43617021,
        16.45744681